### ISSUE TITLE
width and height must be > 0

### ISSUE THREAD

**Issue by HusseinDTS** [Muddz/QuickShot#25]
I tried any view and I had the same problem. do you know why I get this error?

`Process: com.hdts.present, PID: 30499
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hdts.present/com.hdts.present.activity.ActivityMain}: java.lang.IllegalArgumentException: width and height must be > 0
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3308)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7562)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1113)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1080)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1030)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
        at com.muddzdev.quickshot.QuickShot.getBitmap(QuickShot.java:179)
        at com.muddzdev.quickshot.QuickShot.save(QuickShot.java:207)
        at com.hdts.present.activity.ActivityMain.onCreate(ActivityMain.java:85)
        at android.app.Activity.performCreate(Activity.java:7893)
        at android.app.Activity.performCreate(Activity.java:7880)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)`

**Comment by Muddz** [comment]
Hi there. Maybe you are passing af View or Bitmap object which is not inflated, or which is null or which has height + width at 0.
Have you solved the problem? if not, please send me the rest of the code
